### ISSUE TITLE
Upload queue data

### ISSUE THREAD

**Issue by MarcelCutts** [MarcelCutts/patienttracker#4]
# Motivation

We want our capture patient data and make it available on a server for later analysis.

# Tasks

A number of steps are required to get an initial version of this functionality out

- [ ] A function that takes the current data and puts it into the correct JSON schema
- [ ] An asynchronous redux action to ship that data out
- [ ] A button to trigger this
- [ ] Clearing of patient data ONLY IF data uploaded successfully
